### ISSUE TITLE
没有接触过python，百度安好了环境，运行报错

### ISSUE THREAD

**Issue by qinbo1008** [xirtam-ch/JGMAuto#1]
C:\Users\QinBO2\Desktop>python shell.py
  File "shell.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by ZPYhiahiahia** [comment]
是不是改动文件的时候多删了或者多敲了

**Comment by xirtam-zhang** [comment]
看一下第七行是什么？

**Comment by qinbo1008** [comment]
> 看一下第七行是什么？

已经没问题了，一开始不懂github套路直接右键的文件，从“clone or download”下就正常了
